version: '3'

services:
  webserver:
    build: ./docker
    image: test_web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/kike/projects/simple-php7-docker/www:/var/www/html
    links:
      - db

  db:
    image: mysql:5.7
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=db_test

